# Generated by Django 4.1.7 on 2023-03-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
