# Generated by Django 4.1.7 on 2023-03-25 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning', '0002_enseignant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elearning.enseignant')),
            ],
        ),
    ]
