# Generated by Django 4.1.7 on 2023-03-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning', '0004_inscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('maladie', models.BooleanField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
